// The figure in CALORIE CALC.
//
// A glTF with morph targets, blended continuously from one number: body fat.
// The mesh that ships is a placeholder generated by tools/build_body_glb.py; an
// MB-Lab bake exported the same way drops in with no change here, because the
// only contract is the one written in that script — base mesh leanest, morph
// targets in ascending order, and mesh.extras.bodyFat listing the percentage of
// the base and of every target.
//
// Loaded on demand, and only ever once: three is 670 KB and has no business
// being fetched by anyone who opens the food table.

import * as THREE from "./vendor/three/three.module.min.js";
import { GLTFLoader } from "./vendor/three/GLTFLoader.js";

const CYAN = 0x22d3ee;
const cache = new Map();      // sex -> Promise<{ geometry, bodyFat }>

function loadBody(sex) {
  if (!cache.has(sex)) {
    cache.set(sex, new Promise((res, rej) => {
      new GLTFLoader().load("data/body/body-" + sex + ".glb", g => {
        let mesh = null;
        g.scene.traverse(o => { if (o.isMesh && !mesh) mesh = o; });
        if (!mesh) return rej(new Error("no mesh"));
        const bf = (mesh.geometry.userData && mesh.geometry.userData.bodyFat)
          || (g.parser.json.meshes[0].extras || {}).bodyFat;
        res({ geometry: mesh.geometry, bodyFat: bf });
      }, undefined, rej);
    }));
  }
  return cache.get(sex);
}

// The blend. With one parameter swept across N shapes, the influence of each is
// a hat function on the level axis — which makes the result exactly the linear
// interpolation between the two shapes either side, and nothing else.
function weightsFor(levels, bf) {
  const w = new Array(levels.length - 1).fill(0);
  const v = Math.max(levels[0], Math.min(levels[levels.length - 1], bf));
  for (let i = 0; i < levels.length - 1; i++) {
    const a = levels[i], b = levels[i + 1];
    if (v >= a && v <= b) {
      const t = (v - a) / (b - a);
      if (i > 0) w[i - 1] = 1 - t;
      w[i] = t;
      // Every target below the bracket is fully on: the deltas are measured from
      // the base, so leaving them out would snap back to the leanest shape.
      for (let k = 0; k < i - 1; k++) w[k] = 0;
      break;
    }
  }
  return w;
}

export function mount(canvas) {
  if (canvas.__body) return canvas.__body;

  let renderer;
  try {
    renderer = new THREE.WebGLRenderer({ canvas, alpha: true, antialias: true });
  } catch (e) { return null; }
  renderer.setClearAlpha(0);

  const scene = new THREE.Scene();
  // The mesh is authored feet-at-origin in metres, so it is dropped by half its
  // height and the camera sits square on the middle of it. A 1.95 m frame at 26
  // degrees puts the whole figure in the box with a little air top and bottom,
  // and since the vertical field of view maps to the box height, the figure fills
  // whatever height the layout gives it without any per-screen fitting.
  const camera = new THREE.PerspectiveCamera(26, 1, 0.1, 20);
  camera.position.set(0, 0, (1.95 / 2) / Math.tan(26 * Math.PI / 360));
  camera.lookAt(0, 0, 0);

  // Lit the way the rest of the site is: a dark matte body with the cyan coming
  // in from the side, so the silhouette does the reading and the surface only
  // says which way it is facing.
  scene.add(new THREE.HemisphereLight(0x2c3f4d, 0x05080d, 1.1));
  const key = new THREE.DirectionalLight(0xbcd4e2, 1.15);
  key.position.set(-2.2, 2.6, 3.4);
  scene.add(key);
  const rim = new THREE.DirectionalLight(CYAN, 2.3);
  rim.position.set(3.4, 1.4, -2.6);
  scene.add(rim);

  const material = new THREE.MeshStandardMaterial({
    color: 0x1b2a36, roughness: 0.72, metalness: 0.05, flatShading: false
  });

  const pivot = new THREE.Group();
  scene.add(pivot);

  let mesh = null, levels = null, want = { sex: "m", bf: 20 };
  let spin = 0, drag = null, vel = 0, raf = 0, alive = true, dirty = true;
  const still = matchMedia("(prefers-reduced-motion: reduce)").matches;

  const size = () => {
    const r = canvas.getBoundingClientRect();
    const w = Math.max(1, Math.round(r.width)), h = Math.max(1, Math.round(r.height));
    if (canvas.width !== w * devicePixelRatio || canvas.height !== h * devicePixelRatio) {
      renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
      renderer.setSize(w, h, false);
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
      dirty = true;
    }
  };

  const apply = () => {
    if (!mesh || !levels) return;
    const w = weightsFor(levels, want.bf);
    for (let i = 0; i < mesh.morphTargetInfluences.length; i++)
      mesh.morphTargetInfluences[i] = w[i] || 0;
    dirty = true;
  };

  const swap = sex => loadBody(sex).then(b => {
    if (!alive) return;
    if (mesh) { pivot.remove(mesh); }
    mesh = new THREE.Mesh(b.geometry, material);
    mesh.position.y = -0.875;     // centred on the origin, which the camera holds
    levels = b.bodyFat;
    pivot.add(mesh);
    apply();
  }).catch(() => { canvas.setAttribute("data-body-failed", "1"); });

  let loaded = null;

  const tick = () => {
    if (!alive) return;
    raf = requestAnimationFrame(tick);
    size();
    if (drag == null && !still) {
      spin += 0.0042 + vel;
      vel *= 0.94;
      dirty = true;
    } else if (Math.abs(vel) > 1e-5) {
      spin += vel; vel *= 0.9; dirty = true;
    }
    if (!dirty) return;
    pivot.rotation.y = spin;
    renderer.render(scene, camera);
    dirty = false;
  };

  const down = e => {
    drag = (e.touches ? e.touches[0] : e).clientX;
    vel = 0;
  };
  const move = e => {
    if (drag == null) return;
    const x = (e.touches ? e.touches[0] : e).clientX;
    vel = (x - drag) * 0.012;
    spin += vel;
    drag = x;
    dirty = true;
    if (e.cancelable) e.preventDefault();
  };
  const up = () => { drag = null; };

  canvas.addEventListener("pointerdown", down);
  window.addEventListener("pointermove", move, { passive: false });
  window.addEventListener("pointerup", up);
  canvas.addEventListener("touchstart", down, { passive: true });
  window.addEventListener("touchmove", move, { passive: false });
  window.addEventListener("touchend", up);

  tick();

  const api = {
    set(sex, bf) {
      want.bf = bf;
      if (sex !== loaded) { loaded = sex; want.sex = sex; swap(sex); }
      else apply();
    },
    dispose() {
      alive = false;
      cancelAnimationFrame(raf);
      canvas.removeEventListener("pointerdown", down);
      window.removeEventListener("pointermove", move);
      window.removeEventListener("pointerup", up);
      canvas.removeEventListener("touchstart", down);
      window.removeEventListener("touchmove", move);
      window.removeEventListener("touchend", up);
      renderer.dispose();
      delete canvas.__body;
    }
  };
  canvas.__body = api;
  return api;
}
